### ISSUE TITLE
Buy it somewhere

### ISSUE THREAD

**Issue by flakef** [techlobo/ATX_Switch#1]
That's a fantastic thing for pikvm4plus! Is it possible to buy ATX_Switch and ATX Switch Interface adaptors already assembled?

**Comment by techlobo** [comment]
I am afraid not.

I did this for interest / fun, not to run a small business with the associated procurement, manufacturing / testing, packaging / distribution, and support hassles - all of which would have made the price of the products substantially more. This was one of the reasons for making this Open Source.

The products are fairy easy to make though provided you have basic soldering skills, as most of the components are Through Hole (TH). I had the PCB's made by JLCPCB and used their PCBA service to solder the surface mount components prior to delivery. It would probably be possible to get them to also solder the majority of the TH components, but it is likely that you would still need to solder some of the connector components yourself.
